runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: .*
  script: search_app.application

- url: /admin_gate
  script: search_app.application

- url: /admin
  script: search_app.application
  login: admin

libraries:
- name: jinja2
  version: "2.6"
